version: "3"

services:

  eureka-servers:
    container_name: eurekas
    build:
      context: ./eureka-discovery
      dockerfile: Dockerfile
    ports:
     - "8761:8761"


  gateawys:
    container_name: gateways
    build:
      context: ./gateway
      dockerfile: Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-servers:8761/eureka
    depends_on:
      - eureka-servers
    ports:
      - "8888:8880"
      
  dbcustomers:
    container_name: dbcustomers
    image: mysql:latest
    environment:
      
      - MYSQL_DATABASE=dbclient
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306" 
  dbinvoices:
    container_name: dbinvoices
    image: mysql:latest
    environment:
      
      - MYSQL_DATABASE=dbinvoice
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3307" 


  customers:
    container_name: customers
    
    build:
   
      context: ./customer-service
      dockerfile: Dockerfile
    image: ms_customers
    environment:
    - eureka.client.service-url.defaultZone=http://eureka-servers:8761/eureka
    - spring.datasource.url=jdbc:mysql://dbcustomers:3306/dbclients?createDatabaseIfNotExist=true
    - spring.datasource.username=root
    - spring.datasource.password=root
    - spring.datasource.driver-class-name=com.mysql.jdbc.Driver
    - spring.jpa.database=MYSQL
    - spring.jpa.show-sql=true
    - spring.jpa.hibernate.ddl-auto=update
    - spring.jpa.hibernate.naming.strategy=org.hibernet.cfg.ImprovedNamingStrategy
        
     
    depends_on:
      - eureka-servers
      - dbcustomers
    ports:
      - 8082:8082
  invoices:
    container_name: invoices
    
    build:
   
      context: ./billing-service
      dockerfile: Dockerfile
    image: ms_invoices
    environment:
    - eureka.client.service-url.defaultZone=http://eureka-servers:8761/eureka
    - spring.datasource.url=jdbc:mysql://dbcustomers:3306/dbinvoice?createDatabaseIfNotExist=true
    - spring.datasource.username=root
    - spring.datasource.password=root
    - spring.datasource.driver-class-name=com.mysql.jdbc.Driver
    - spring.jpa.database=MYSQL
    - spring.jpa.show-sql=true
    - spring.jpa.hibernate.ddl-auto=update
    - spring.jpa.hibernate.naming.strategy=org.hibernet.cfg.ImprovedNamingStrategy
        
     
    depends_on:
      - eureka-servers
      - dbcustomers
    ports:
      - 8083:8083
  DB_livre:
    container_name: DB_livre
    image: mongo
    restart: always
    ports:
      - 27019:27017
  
  MS_livre: 
    container_name: MS_livre
    build: ./MS_livres
    image: ms_livre
    ports:
      - 8700:8700
    environment:
     - PORT=8700
     - EUREKA_HOST=eureka-servers
     - EUREKA_PORT=8761
     - DATABASE=DB_livre
     - HOSTNAME=MS_livre
     - ADRESSE=MS_livre  
     - DBPORT=27017
    depends_on:
     - DB_livre    
     - eureka-servers
  MS_commande: 
    container_name: MS_commande
    build: ./MS_Commande
    image: ms_commande
    ports:
      - 8084:8084
    environment:
     - eureka.client.service-url.defaultZone=http://eureka-servers:8761/eureka
     - spring.datasource.url=jdbc:mysql://dbcustomers:3306/dbcommande?createDatabaseIfNotExist=true
     - spring.datasource.username=root
     - spring.datasource.password=root
     - spring.datasource.driver-class-name=com.mysql.jdbc.Driver
     - spring.jpa.database=MYSQL
     - spring.jpa.show-sql=true
     - spring.jpa.hibernate.ddl-auto=update
     - spring.jpa.hibernate.naming.strategy=org.hibernet.cfg.ImprovedNamingStrategy
    depends_on:
     - dbcustomers 
     - eureka-servers     
  